/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SchemaDotjsonRouteImport } from "./routes/schema[.]json";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as AuthRouteRouteImport } from "./routes/auth/route";
import { Route as HomeRouteRouteImport } from "./routes/_home/route";
import { Route as McpIndexRouteImport } from "./routes/mcp/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as HomeIndexRouteImport } from "./routes/_home/index";
import { Route as PrinterResumeIdRouteImport } from "./routes/printer/$resumeId";
import { Route as AuthVerify2faBackupRouteImport } from "./routes/auth/verify-2fa-backup";
import { Route as AuthVerify2faRouteImport } from "./routes/auth/verify-2fa";
import { Route as AuthResumePasswordRouteImport } from "./routes/auth/resume-password";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthOauthRouteImport } from "./routes/auth/oauth";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as DotwellKnownOpenidConfigurationRouteImport } from "./routes/[.]well-known/openid-configuration";
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from "./routes/[.]well-known/oauth-protected-resource";
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from "./routes/[.]well-known/oauth-authorization-server";
import { Route as UsernameSlugRouteImport } from "./routes/$username/$slug";
import { Route as BuilderResumeIdRouteRouteImport } from "./routes/builder/$resumeId/route";
import { Route as DashboardResumesIndexRouteImport } from "./routes/dashboard/resumes/index";
import { Route as DashboardJobSearchIndexRouteImport } from "./routes/dashboard/job-search/index";
import { Route as BuilderResumeIdIndexRouteImport } from "./routes/builder/$resumeId/index";
import { Route as UploadsUserIdSplatRouteImport } from "./routes/uploads/$userId.$";
import { Route as DashboardSettingsProfileRouteImport } from "./routes/dashboard/settings/profile";
import { Route as DashboardSettingsPreferencesRouteImport } from "./routes/dashboard/settings/preferences";
import { Route as DashboardSettingsJobSearchRouteImport } from "./routes/dashboard/settings/job-search";
import { Route as DashboardSettingsDangerZoneRouteImport } from "./routes/dashboard/settings/danger-zone";
import { Route as DashboardSettingsApiKeysRouteImport } from "./routes/dashboard/settings/api-keys";
import { Route as DashboardSettingsAiRouteImport } from "./routes/dashboard/settings/ai";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiOpenapiSplatRouteImport } from "./routes/api/openapi.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as DotwellKnownOauthProtectedResourceSplatRouteImport } from "./routes/[.]well-known/oauth-protected-resource.$";
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from "./routes/[.]well-known/oauth-authorization-server.$";
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from "./routes/[.]well-known/mcp/server-card[.]json";
import { Route as DashboardSettingsAuthenticationIndexRouteImport } from "./routes/dashboard/settings/authentication/index";
import { Route as DashboardAdminUsersIndexRouteImport } from "./routes/dashboard/admin/users/index";

const SchemaDotjsonRoute = SchemaDotjsonRouteImport.update({
  id: "/schema.json",
  path: "/schema.json",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: "/_home",
  getParentRoute: () => rootRouteImport,
} as any);
const McpIndexRoute = McpIndexRouteImport.update({
  id: "/mcp/",
  path: "/mcp/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => HomeRouteRoute,
} as any);
const PrinterResumeIdRoute = PrinterResumeIdRouteImport.update({
  id: "/printer/$resumeId",
  path: "/printer/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthVerify2faBackupRoute = AuthVerify2faBackupRouteImport.update({
  id: "/verify-2fa-backup",
  path: "/verify-2fa-backup",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: "/verify-2fa",
  path: "/verify-2fa",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResumePasswordRoute = AuthResumePasswordRouteImport.update({
  id: "/resume-password",
  path: "/resume-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: "/oauth",
  path: "/oauth",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: "/.well-known/openid-configuration",
    path: "/.well-known/openid-configuration",
    getParentRoute: () => rootRouteImport,
  } as any);
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: "/.well-known/oauth-protected-resource",
    path: "/.well-known/oauth-protected-resource",
    getParentRoute: () => rootRouteImport,
  } as any);
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: "/.well-known/oauth-authorization-server",
    path: "/.well-known/oauth-authorization-server",
    getParentRoute: () => rootRouteImport,
  } as any);
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: "/$username/$slug",
  path: "/$username/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const BuilderResumeIdRouteRoute = BuilderResumeIdRouteRouteImport.update({
  id: "/builder/$resumeId",
  path: "/builder/$resumeId",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: "/resumes/",
  path: "/resumes/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const DashboardJobSearchIndexRoute = DashboardJobSearchIndexRouteImport.update({
  id: "/job-search/",
  path: "/job-search/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const BuilderResumeIdIndexRoute = BuilderResumeIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BuilderResumeIdRouteRoute,
} as any);
const UploadsUserIdSplatRoute = UploadsUserIdSplatRouteImport.update({
  id: "/uploads/$userId/$",
  path: "/uploads/$userId/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: "/settings/profile",
    path: "/settings/profile",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: "/settings/preferences",
    path: "/settings/preferences",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsJobSearchRoute =
  DashboardSettingsJobSearchRouteImport.update({
    id: "/settings/job-search",
    path: "/settings/job-search",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsDangerZoneRoute =
  DashboardSettingsDangerZoneRouteImport.update({
    id: "/settings/danger-zone",
    path: "/settings/danger-zone",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: "/settings/api-keys",
    path: "/settings/api-keys",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardSettingsAiRoute = DashboardSettingsAiRouteImport.update({
  id: "/settings/ai",
  path: "/settings/ai",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOpenapiSplatRoute = ApiOpenapiSplatRouteImport.update({
  id: "/api/openapi/$",
  path: "/api/openapi/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownOauthProtectedResourceSplatRoute =
  DotwellKnownOauthProtectedResourceSplatRouteImport.update({
    id: "/$",
    path: "/$",
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any);
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: "/$",
    path: "/$",
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any);
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: "/.well-known/mcp/server-card.json",
    path: "/.well-known/mcp/server-card.json",
    getParentRoute: () => rootRouteImport,
  } as any);
const DashboardSettingsAuthenticationIndexRoute =
  DashboardSettingsAuthenticationIndexRouteImport.update({
    id: "/settings/authentication/",
    path: "/settings/authentication/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: "/admin/users/",
    path: "/admin/users/",
    getParentRoute: () => DashboardRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/schema.json": typeof SchemaDotjsonRoute;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/.well-known/oauth-authorization-server": typeof DotwellKnownOauthAuthorizationServerRouteWithChildren;
  "/.well-known/oauth-protected-resource": typeof DotwellKnownOauthProtectedResourceRouteWithChildren;
  "/.well-known/openid-configuration": typeof DotwellKnownOpenidConfigurationRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/oauth": typeof AuthOauthRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/mcp/": typeof McpIndexRoute;
  "/.well-known/mcp/server-card.json": typeof DotwellKnownMcpServerCardDotjsonRoute;
  "/.well-known/oauth-authorization-server/$": typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/job-search": typeof DashboardSettingsJobSearchRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/job-search/": typeof DashboardJobSearchIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/dashboard/admin/users/": typeof DashboardAdminUsersIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesByTo {
  "/schema.json": typeof SchemaDotjsonRoute;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/.well-known/oauth-authorization-server": typeof DotwellKnownOauthAuthorizationServerRouteWithChildren;
  "/.well-known/oauth-protected-resource": typeof DotwellKnownOauthProtectedResourceRouteWithChildren;
  "/.well-known/openid-configuration": typeof DotwellKnownOpenidConfigurationRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/oauth": typeof AuthOauthRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/": typeof HomeIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/mcp": typeof McpIndexRoute;
  "/.well-known/mcp/server-card.json": typeof DotwellKnownMcpServerCardDotjsonRoute;
  "/.well-known/oauth-authorization-server/$": typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/job-search": typeof DashboardSettingsJobSearchRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId": typeof BuilderResumeIdIndexRoute;
  "/dashboard/job-search": typeof DashboardJobSearchIndexRoute;
  "/dashboard/resumes": typeof DashboardResumesIndexRoute;
  "/dashboard/admin/users": typeof DashboardAdminUsersIndexRoute;
  "/dashboard/settings/authentication": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_home": typeof HomeRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/schema.json": typeof SchemaDotjsonRoute;
  "/builder/$resumeId": typeof BuilderResumeIdRouteRouteWithChildren;
  "/$username/$slug": typeof UsernameSlugRoute;
  "/.well-known/oauth-authorization-server": typeof DotwellKnownOauthAuthorizationServerRouteWithChildren;
  "/.well-known/oauth-protected-resource": typeof DotwellKnownOauthProtectedResourceRouteWithChildren;
  "/.well-known/openid-configuration": typeof DotwellKnownOpenidConfigurationRoute;
  "/api/health": typeof ApiHealthRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/oauth": typeof AuthOauthRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/resume-password": typeof AuthResumePasswordRoute;
  "/auth/verify-2fa": typeof AuthVerify2faRoute;
  "/auth/verify-2fa-backup": typeof AuthVerify2faBackupRoute;
  "/printer/$resumeId": typeof PrinterResumeIdRoute;
  "/_home/": typeof HomeIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/mcp/": typeof McpIndexRoute;
  "/.well-known/mcp/server-card.json": typeof DotwellKnownMcpServerCardDotjsonRoute;
  "/.well-known/oauth-authorization-server/$": typeof DotwellKnownOauthAuthorizationServerSplatRoute;
  "/.well-known/oauth-protected-resource/$": typeof DotwellKnownOauthProtectedResourceSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/openapi/$": typeof ApiOpenapiSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/dashboard/settings/ai": typeof DashboardSettingsAiRoute;
  "/dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute;
  "/dashboard/settings/danger-zone": typeof DashboardSettingsDangerZoneRoute;
  "/dashboard/settings/job-search": typeof DashboardSettingsJobSearchRoute;
  "/dashboard/settings/preferences": typeof DashboardSettingsPreferencesRoute;
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute;
  "/uploads/$userId/$": typeof UploadsUserIdSplatRoute;
  "/builder/$resumeId/": typeof BuilderResumeIdIndexRoute;
  "/dashboard/job-search/": typeof DashboardJobSearchIndexRoute;
  "/dashboard/resumes/": typeof DashboardResumesIndexRoute;
  "/dashboard/admin/users/": typeof DashboardAdminUsersIndexRoute;
  "/dashboard/settings/authentication/": typeof DashboardSettingsAuthenticationIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/dashboard"
    | "/schema.json"
    | "/builder/$resumeId"
    | "/$username/$slug"
    | "/.well-known/oauth-authorization-server"
    | "/.well-known/oauth-protected-resource"
    | "/.well-known/openid-configuration"
    | "/api/health"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/oauth"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/printer/$resumeId"
    | "/auth/"
    | "/dashboard/"
    | "/mcp/"
    | "/.well-known/mcp/server-card.json"
    | "/.well-known/oauth-authorization-server/$"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/job-search"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId/"
    | "/dashboard/job-search/"
    | "/dashboard/resumes/"
    | "/dashboard/admin/users/"
    | "/dashboard/settings/authentication/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/schema.json"
    | "/$username/$slug"
    | "/.well-known/oauth-authorization-server"
    | "/.well-known/oauth-protected-resource"
    | "/.well-known/openid-configuration"
    | "/api/health"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/oauth"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/printer/$resumeId"
    | "/"
    | "/auth"
    | "/dashboard"
    | "/mcp"
    | "/.well-known/mcp/server-card.json"
    | "/.well-known/oauth-authorization-server/$"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/job-search"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId"
    | "/dashboard/job-search"
    | "/dashboard/resumes"
    | "/dashboard/admin/users"
    | "/dashboard/settings/authentication";
  id:
    | "__root__"
    | "/_home"
    | "/auth"
    | "/dashboard"
    | "/schema.json"
    | "/builder/$resumeId"
    | "/$username/$slug"
    | "/.well-known/oauth-authorization-server"
    | "/.well-known/oauth-protected-resource"
    | "/.well-known/openid-configuration"
    | "/api/health"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/oauth"
    | "/auth/register"
    | "/auth/reset-password"
    | "/auth/resume-password"
    | "/auth/verify-2fa"
    | "/auth/verify-2fa-backup"
    | "/printer/$resumeId"
    | "/_home/"
    | "/auth/"
    | "/dashboard/"
    | "/mcp/"
    | "/.well-known/mcp/server-card.json"
    | "/.well-known/oauth-authorization-server/$"
    | "/.well-known/oauth-protected-resource/$"
    | "/api/auth/$"
    | "/api/openapi/$"
    | "/api/rpc/$"
    | "/dashboard/settings/ai"
    | "/dashboard/settings/api-keys"
    | "/dashboard/settings/danger-zone"
    | "/dashboard/settings/job-search"
    | "/dashboard/settings/preferences"
    | "/dashboard/settings/profile"
    | "/uploads/$userId/$"
    | "/builder/$resumeId/"
    | "/dashboard/job-search/"
    | "/dashboard/resumes/"
    | "/dashboard/admin/users/"
    | "/dashboard/settings/authentication/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  SchemaDotjsonRoute: typeof SchemaDotjsonRoute;
  BuilderResumeIdRouteRoute: typeof BuilderResumeIdRouteRouteWithChildren;
  UsernameSlugRoute: typeof UsernameSlugRoute;
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren;
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren;
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  PrinterResumeIdRoute: typeof PrinterResumeIdRoute;
  McpIndexRoute: typeof McpIndexRoute;
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiOpenapiSplatRoute: typeof ApiOpenapiSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
  UploadsUserIdSplatRoute: typeof UploadsUserIdSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/schema.json": {
      id: "/schema.json";
      path: "/schema.json";
      fullPath: "/schema.json";
      preLoaderRoute: typeof SchemaDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_home": {
      id: "/_home";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof HomeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mcp/": {
      id: "/mcp/";
      path: "/mcp";
      fullPath: "/mcp/";
      preLoaderRoute: typeof McpIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexRouteImport;
      parentRoute: typeof HomeRouteRoute;
    };
    "/printer/$resumeId": {
      id: "/printer/$resumeId";
      path: "/printer/$resumeId";
      fullPath: "/printer/$resumeId";
      preLoaderRoute: typeof PrinterResumeIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/verify-2fa-backup": {
      id: "/auth/verify-2fa-backup";
      path: "/verify-2fa-backup";
      fullPath: "/auth/verify-2fa-backup";
      preLoaderRoute: typeof AuthVerify2faBackupRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/verify-2fa": {
      id: "/auth/verify-2fa";
      path: "/verify-2fa";
      fullPath: "/auth/verify-2fa";
      preLoaderRoute: typeof AuthVerify2faRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/resume-password": {
      id: "/auth/resume-password";
      path: "/resume-password";
      fullPath: "/auth/resume-password";
      preLoaderRoute: typeof AuthResumePasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/oauth": {
      id: "/auth/oauth";
      path: "/oauth";
      fullPath: "/auth/oauth";
      preLoaderRoute: typeof AuthOauthRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/openid-configuration": {
      id: "/.well-known/openid-configuration";
      path: "/.well-known/openid-configuration";
      fullPath: "/.well-known/openid-configuration";
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/oauth-protected-resource": {
      id: "/.well-known/oauth-protected-resource";
      path: "/.well-known/oauth-protected-resource";
      fullPath: "/.well-known/oauth-protected-resource";
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/oauth-authorization-server": {
      id: "/.well-known/oauth-authorization-server";
      path: "/.well-known/oauth-authorization-server";
      fullPath: "/.well-known/oauth-authorization-server";
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$username/$slug": {
      id: "/$username/$slug";
      path: "/$username/$slug";
      fullPath: "/$username/$slug";
      preLoaderRoute: typeof UsernameSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/builder/$resumeId": {
      id: "/builder/$resumeId";
      path: "/builder/$resumeId";
      fullPath: "/builder/$resumeId";
      preLoaderRoute: typeof BuilderResumeIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/resumes/": {
      id: "/dashboard/resumes/";
      path: "/resumes";
      fullPath: "/dashboard/resumes/";
      preLoaderRoute: typeof DashboardResumesIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/job-search/": {
      id: "/dashboard/job-search/";
      path: "/job-search";
      fullPath: "/dashboard/job-search/";
      preLoaderRoute: typeof DashboardJobSearchIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/builder/$resumeId/": {
      id: "/builder/$resumeId/";
      path: "/";
      fullPath: "/builder/$resumeId/";
      preLoaderRoute: typeof BuilderResumeIdIndexRouteImport;
      parentRoute: typeof BuilderResumeIdRouteRoute;
    };
    "/uploads/$userId/$": {
      id: "/uploads/$userId/$";
      path: "/uploads/$userId/$";
      fullPath: "/uploads/$userId/$";
      preLoaderRoute: typeof UploadsUserIdSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/profile": {
      id: "/dashboard/settings/profile";
      path: "/settings/profile";
      fullPath: "/dashboard/settings/profile";
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/preferences": {
      id: "/dashboard/settings/preferences";
      path: "/settings/preferences";
      fullPath: "/dashboard/settings/preferences";
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/job-search": {
      id: "/dashboard/settings/job-search";
      path: "/settings/job-search";
      fullPath: "/dashboard/settings/job-search";
      preLoaderRoute: typeof DashboardSettingsJobSearchRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/danger-zone": {
      id: "/dashboard/settings/danger-zone";
      path: "/settings/danger-zone";
      fullPath: "/dashboard/settings/danger-zone";
      preLoaderRoute: typeof DashboardSettingsDangerZoneRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/api-keys": {
      id: "/dashboard/settings/api-keys";
      path: "/settings/api-keys";
      fullPath: "/dashboard/settings/api-keys";
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/settings/ai": {
      id: "/dashboard/settings/ai";
      path: "/settings/ai";
      fullPath: "/dashboard/settings/ai";
      preLoaderRoute: typeof DashboardSettingsAiRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/openapi/$": {
      id: "/api/openapi/$";
      path: "/api/openapi/$";
      fullPath: "/api/openapi/$";
      preLoaderRoute: typeof ApiOpenapiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/oauth-protected-resource/$": {
      id: "/.well-known/oauth-protected-resource/$";
      path: "/$";
      fullPath: "/.well-known/oauth-protected-resource/$";
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceSplatRouteImport;
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute;
    };
    "/.well-known/oauth-authorization-server/$": {
      id: "/.well-known/oauth-authorization-server/$";
      path: "/$";
      fullPath: "/.well-known/oauth-authorization-server/$";
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport;
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute;
    };
    "/.well-known/mcp/server-card.json": {
      id: "/.well-known/mcp/server-card.json";
      path: "/.well-known/mcp/server-card.json";
      fullPath: "/.well-known/mcp/server-card.json";
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/settings/authentication/": {
      id: "/dashboard/settings/authentication/";
      path: "/settings/authentication";
      fullPath: "/dashboard/settings/authentication/";
      preLoaderRoute: typeof DashboardSettingsAuthenticationIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/dashboard/admin/users/": {
      id: "/dashboard/admin/users/";
      path: "/admin/users";
      fullPath: "/dashboard/admin/users/";
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute;
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
};

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthOauthRoute: typeof AuthOauthRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthResumePasswordRoute: typeof AuthResumePasswordRoute;
  AuthVerify2faRoute: typeof AuthVerify2faRoute;
  AuthVerify2faBackupRoute: typeof AuthVerify2faBackupRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthRoute: AuthOauthRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResumePasswordRoute: AuthResumePasswordRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthVerify2faBackupRoute: AuthVerify2faBackupRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardSettingsAiRoute: typeof DashboardSettingsAiRoute;
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute;
  DashboardSettingsDangerZoneRoute: typeof DashboardSettingsDangerZoneRoute;
  DashboardSettingsJobSearchRoute: typeof DashboardSettingsJobSearchRoute;
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute;
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute;
  DashboardJobSearchIndexRoute: typeof DashboardJobSearchIndexRoute;
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute;
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute;
  DashboardSettingsAuthenticationIndexRoute: typeof DashboardSettingsAuthenticationIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsAiRoute: DashboardSettingsAiRoute,
  DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
  DashboardSettingsDangerZoneRoute: DashboardSettingsDangerZoneRoute,
  DashboardSettingsJobSearchRoute: DashboardSettingsJobSearchRoute,
  DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardJobSearchIndexRoute: DashboardJobSearchIndexRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
  DashboardSettingsAuthenticationIndexRoute:
    DashboardSettingsAuthenticationIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

interface BuilderResumeIdRouteRouteChildren {
  BuilderResumeIdIndexRoute: typeof BuilderResumeIdIndexRoute;
}

const BuilderResumeIdRouteRouteChildren: BuilderResumeIdRouteRouteChildren = {
  BuilderResumeIdIndexRoute: BuilderResumeIdIndexRoute,
};

const BuilderResumeIdRouteRouteWithChildren =
  BuilderResumeIdRouteRoute._addFileChildren(BuilderResumeIdRouteRouteChildren);

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute;
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerSplatRoute:
      DotwellKnownOauthAuthorizationServerSplatRoute,
  };

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  );

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceSplatRoute: typeof DotwellKnownOauthProtectedResourceSplatRoute;
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceSplatRoute:
      DotwellKnownOauthProtectedResourceSplatRoute,
  };

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SchemaDotjsonRoute: SchemaDotjsonRoute,
  BuilderResumeIdRouteRoute: BuilderResumeIdRouteRouteWithChildren,
  UsernameSlugRoute: UsernameSlugRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiHealthRoute: ApiHealthRoute,
  PrinterResumeIdRoute: PrinterResumeIdRoute,
  McpIndexRoute: McpIndexRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiSplatRoute: ApiOpenapiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  UploadsUserIdSplatRoute: UploadsUserIdSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
